### ISSUE TITLE
Getting error when using plugin with Webpack 4.6

### ISSUE THREAD

**Issue by Luckyfella73** [zanettin/react-dev-utils#1]
Hi,

I used the react-dev-utils successfully working with webpack 3.x. I now switched to
Webpack 4.6 and can't start webpack-devserver anymore without getting the following error message:

```
/Users/myUsername/projectName/node_modules/react-dev-utils/WatchMissingNodeModulesPlugin.js:25
      if (missingDeps.some(file => file.indexOf(nodeModulesPath) !== -1)) {
                      ^

TypeError: missingDeps.some is not a function
    at compiler.plugin (/Users/myUsername/projectName/node_modules/react-dev-utils/WatchMissingNodeModulesPlugin.js:25:23)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/myUsername/projectName/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/myUsername/projectName/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.emitAssets (/Users/myUsername/projectName/node_modules/webpack/lib/Compiler.js:307:19)
    at onCompiled (/Users/myUsername/projectName/node_modules/webpack/lib/Watching.js:50:19)
    at hooks.afterCompile.callAsync.err (/Users/myUsername/projectName/node_modules/webpack/lib/Compiler.js:487:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/myUsername/projectName/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/myUsername/projectName/node_modules/tapable/lib/Hook.js:35:21)
    at compilation.seal.err (/Users/myUsername/projectName/node_modules/webpack/lib/Compiler.js:484:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/myUsername/projectName/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/myUsername/projectName/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeAssets.callAsync.err (/Users/myUsername/projectName/node_modules/webpack/lib/Compilation.js:966:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/myUsername/projectName/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/myUsername/projectName/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeChunkAssets.callAsync.err (/Users/myUsername/projectName/node_modules/webpack/lib/Compilation.js:957:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/myUsername/projectName/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
```

In my webpack.config.js I call the plugin like the docs tells:
`ifDevelopment(new WatchMissingNodeModulesPlugin(path.resolve('node_modules')))`

Any ideas where I could look for issues producing this error?

**Comment by Luckyfella73** [comment]
Hi @zanettin 
thank you for your fast response! Installing the babel version you suggested didn't solve the error unfortunately (I allready had webpack 4.6.0 and dev server 3.1.3 installed). But then I guess the problem is caused by something else. I'm going to inspect the tread you linked to.

Thank you!
