### ISSUE TITLE
TypeError: missingDeps.some is not a function

### ISSUE THREAD

**Issue by liuzhiyang0113** [zanettin/react-dev-utils#2]
i use webpack@4.19.0 and react-dev-utils@6.0.0-next.b2fd8db8, when i npm run start ,it don't work.

/Users/mac/Desktop/study/webpack-study/demo1/scripts/start.js:11
  throw err;
  ^

TypeError: missingDeps.some is not a function
    at compiler.plugin (/Users/mac/Desktop/study/webpack-study/demo1/node_modules/react-dev-utils/WatchMissingNodeModulesPlugin.js:25:23)
    at _err0 (eval at create (/Users/mac/Desktop/study/webpack-study/demo1/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at Promise.resolve.then.then.then.then.then.then.then.then.catch.then.then.then (/Users/mac/Desktop/study/webpack-study/demo1/node_modules/html-webpack-plugin/index.js:224:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! demo1@0.1.0 start: `node scripts/start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the demo1@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by zanettin** [comment]
hi @liuzhiyang0113 
thanks for your issue creation. guess you want to creat an issue over at the official react github page. this repo was just created during webpack4 migration. thanks and have a nice day 👍
